.PHONY: clean All

All:
	@echo "----------Building project:[ polTorrent - Debug ]----------"
	@cd "polTorrent" && "$(MAKE)" -f  "polTorrent.mk"
clean:
	@echo "----------Cleaning project:[ polTorrent - Debug ]----------"
	@cd "polTorrent" && "$(MAKE)" -f  "polTorrent.mk" clean
